# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin_sheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
