# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
