# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signin_sheets', '0002_auto_20170701_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
