# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin_sheets', '0003_event_event_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
