# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin_sheets', '0004_auto_20170702_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signin_sheets.Event'),
            preserve_default=False,
        ),
    ]
