# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin_sheets', '0005_eventparticipant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signin_sheets.Event'),
        ),
    ]
